DROP TABLE IF EXISTS offers CASCADE;

CREATE TABLE offers (
  id SERIAL PRIMARY KEY NOT NULL,
  request_id INTEGER REFERENCES requests(id) ON DELETE CASCADE,
  provider_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  quote VARCHAR(30),
  offer_comment TEXT
);